name: Build and test

on:
  push:
  pull_request:
    branches: [main]

jobs:

  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x, 20.x, 22.x]
        include:
          - os: macos-latest
            node-version: 18.x
          - os: macos-latest
            node-version: 20.x
            experimental: true
          - os: macos-latest
            node-version: 22.x
            experimental: true
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
        shell: bash
      - run: yarn run dist:ci
        shell: bash
      - run: yarn link
        shell: bash
      - run: yarn run example:link
        shell: bash
      - run: yarn run example:install
        shell: bash
      - run: yarn run example:test:unit
        shell: bash
      - run: yarn run example:test:cy:run
        shell: bash